/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Agencies: () => import('#controllers/agencies_controller'),
  Analytic: () => import('#controllers/analytic_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Banks: () => import('#controllers/banks_controller'),
  Comparisons: () => import('#controllers/comparisons_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PublicPages: () => import('#controllers/public_pages_controller'),
  Session: () => import('#controllers/session_controller'),
  Tariffs: () => import('#controllers/tariffs_controller'),
}
